### ISSUE TITLE
Feature request of sorts.

### ISSUE THREAD

**Issue by Ming-Kerr** [rppicomidi/midi-multistream2usbdev#1]
I wonder if the author would be interested in modifying the code to work with the pico midi hat below, making an (up to) 6in 6out usb midi interface?
Gerbers are available to fab own PCB.

https://github.com/diyelectromusic/sdemp_pcbs/tree/main/PicoMIDIRouter

![PicoMIDIRouter - pcb](https://github.com/rppicomidi/midi-multistream2usbdev/assets/84568533/1deb7717-d371-44e7-be3b-a4d7871225f7)
![PicoMIDIRouter - sch](https://github.com/rppicomidi/midi-multistream2usbdev/assets/84568533/fb780171-2d52-4e51-9c07-6524d6409db0)

Cheers.

**Comment by rppicomidi** [comment]
@Ming-Kerr I am not interested in building this board and writing code for it. I have no need to send more than 2 channels of MIDI IN to my computer, any my hand-wired device works fine for me. I am happy to help you do it yourself for your own project.

You are correct it would be simplest to start with this project's source because of the way it manages USB descriptors and multiple MIDI streams. You will wind up using the libraries already added to this project plus [midi_uart_lib](https://github.com/rppicomidi/midi_uart_lib) to manage all of the serial ports. Just be aware that I have never tested [midi_uart_lib](https://github.com/rppicomidi/midi_uart_lib) with both serial ports at once, so you might prefer to start out your debugging with having your software only support UART 1 and the 4 PIO UARTs.

Here is some advice to get you started.

First, copy this project source code to your own project. It is MIT license, so have at it. Make sure it builds.

Next, add [midi_uart_lib](https://github.com/rppicomidi/midi_uart_lib) to your project and make it build. Be aware that [midi_uart_lib](https://github.com/rppicomidi/midi_uart_lib) uses [ring_buffer_lib](https://github.com/rppicomidi/ring_buffer_lib) too, but expects it in a different place, so you may have issues building.

Next, you will need to modify the USB descriptor to support 6 streams in and 6 out. Just modify the line with
`CFG_TUD_MIDI_NUMCABLES_IN 2`
in `tusb_config.h` to change 2 to 6
In `usb_descriptors.c`, modify `string_desc_arr[]` to have the the other 4 input ports properly labeled.
In `main.c`, create 4 PIO MIDI UARTs instead of 2. You will also need to create to 2 regular UARTs using [midi_uart_lib](https://github.com/rppicomidi/midi_uart_lib) function `midi_uart_configure()`. Then modify the `midi_task()` function and the functions it calls to route data in from both UARTs to the PC's MIDI IN ports and route data out from the PC MIDI OUT ports. You will need to call functions from [midi_uart_lib](https://github.com/rppicomidi/midi_uart_lib) as well as [pio_midi_uart_lib](https://github.com/rppicomidi/pio_midi_uart_lib) to do this.

Have a go, and if you need more help, please ask on this thread. One thing to be aware. The board design you attached has no debug capability. The SWD ports are not routed. The UARTs and the USB port are consumed by MIDI, so you can't have a console interface unless you make your USB device port enumerate as a composite device that supports both MIDI class and CDC class. That is possible with TinyUSB, but I have not done it and am not sure how well it integrates with Pico SDK `stdio` library.

**Comment by Ming-Kerr** [comment]
Thanks for the detailed response.
I had already delved a little into the code, and it should be relatively easy to match up pins for a working, but incomplete USB interface to begin with.
I have ordered some of these boards and will construct one to experiment.

Thanks again.

**Comment by rppicomidi** [comment]
@Ming-Kerr I updated [midi_uart_lib](https://github.com/rppicomidi/midi_uart_lib) to expect the [ring_buffer_lib](https://github.com/rppicomidi/ring_buffer_lib) directory as the `midi_uart_lib` directory. I have been meaning to do this for some time, but I have been putting it off until someone had a project that required both because it meant I had to update other projects that use it. This update should make building your code simpler.

**Comment by Ming-Kerr** [comment]
Received the PCBs, have constructed one and got it working as a PIO only 4inx4out midi interface without too much bother using the changes to settings in the files mentioned above. Tested briefly in The Reaper DAW and works as expected.
When I simply #include "midi_uart_lib.h" in the main.c file tho, it compiles OK, PIO_MIDI ins continue to work, but all the midi outs stop functioning.
I'm also at a bit of a loss as to how to combine the hardware midi_uart_lib uarts and pio midi uarts.

**Comment by Ming-Kerr** [comment]
Have spent some more time on this today.
Was a bit confused using both PIO_MIDI and HW UARTs, but have now got to the point where USB IO/s are mapping OK, all 4 PIO_UARTS are working and one HW UART is also working. The code itself needs some tidying up.

https://github.com/Ming-Kerr/midi-multistream2usbdev

Do any examples exist how to use both UARTS with midi_uart_lib?
Cheers.

**Comment by Ming-Kerr** [comment]
I appear to have managed to get this working as full 6in/6out midi interface now.
Created two independent HW UART instances and adjusted code to suit.
Needs some thorough testing and code tidying, which I will shortly try and do, but IO's in Reaper DAW all seem OK.

Thanks for these libs.

**Comment by rppicomidi** [comment]
@Ming-Kerr Great progress! But to answer your question, sorry, no. Your project will be the first. In all my work, UART 0 is used as a serial port console for debugging. The [midi2usbhost](https://github.com/rppicomidi/midi2usbhost) project allows you to choose to use UART 1 or UART 0, but not both.

That reminds me, you should probably disable UART stdio prints or else when your application calls the TinyUSB `board_init()` function, it will set up UART 0 for debug console. Add to `CMakeLists.txt` the line
```
pico_enable_stdio_uart(${PROJECT} 0)
```
Also, because you are using the USB device interface for MIDI, it will not hurt to add
```
pico_enable_stdio_usb(${PROJECT} 0)
```
to your file, too.

**Comment by rppicomidi** [comment]
@Ming-Kerr Wow, you fixed your issues before I could write a response. That's super fast. When you are done here, may I ask you to please close this issue? Thank you for pushing the envelope.

**Comment by Ming-Kerr** [comment]
LOL. Yes, I had added parts into the CMakeLists file already, though I also plan to rem out or remove debug messages.
I also took a guess at individual named instances for uart0 & uart1, and it just worked first time.
It's a patchwork, but working...
![Pi Pico MIDI Hat - Reaper Devices](https://github.com/rppicomidi/midi-multistream2usbdev/assets/84568533/e079df8b-fb16-40d6-bcb3-d000f9aca914)

**Comment by Ming-Kerr** [comment]
Cheers now.
